CREATE ROLE rett WITH LOGIN PASSWORD 'rett1234'
  CREATEDB
  NOCREATEROLE
  NOSUPERUSER;

CREATE DATABASE rett OWNER rett;

CREATE ROLE app_readwrite WITH LOGIN PASSWORD 'change_me' NOCREATEDB NOCREATEROLE NOSUPERUSER;
CREATE ROLE app_readonly  WITH LOGIN PASSWORD 'change_me' NOCREATEDB NOCREATEROLE NOSUPERUSER;
